project_id = "fgbxxiscycbvodgguafh"

[functions.generate-dxf]
verify_jwt = true

[functions.generate-kml]
verify_jwt = true

[functions.ai-matricula]
verify_jwt = false

[functions.ai-matricula-chat]
verify_jwt = false
